Importing the dependencies

In [1]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Data Collection and Preprocessing

In [30]:
#Loading the data from the csv file to a panda dataframe
movies_data = pd.read_csv('/content/movies.csv')

In [31]:
#Printing the first 5 rows of the dataframe
movies_data.head()

index  ...           director
0      0  ...      James Cameron
1      1  ...     Gore Verbinski
2      2  ...         Sam Mendes
3      3  ...  Christopher Nolan
4      4  ...     Andrew Stanton

[5 rows x 24 columns]

In [32]:
#No.of rows and columns in the dataframe

movies_data.shape

(4803, 24)

In [36]:
#Selecting the relavant features for recommendation

selected_features = ['genres','keywords','overview','crew','director']
print(selected_features)

['genres', 'keywords', 'overview', 'crew', 'director']


In [37]:
#Replacing the null values with null string

for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')

In [38]:
#Combining all the 5 selected features

combined_features = movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['overview']+' '+movies_data['crew']+' '+movies_data['director']

In [40]:
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  A newlywed couple's honeymoon ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      When ambitious New York attorney Sam is sent...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object


In [42]:
#Converting the text data to feature vectors

vectorizer = TfidfVectorizer()

In [43]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [44]:
print(feature_vectors)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 885586 stored elements and shape (4803, 234398)>
  Coords	Values
  (0, 183013)	0.004861679100873302
  (0, 183184)	0.005609047479849538
  (0, 198186)	0.006928460299613353
  (0, 223384)	0.006458780191409505
  (0, 198655)	0.00648493328205602
  (0, 193345)	0.012188928997578324
  (0, 191458)	0.01267482139788015
  (0, 199872)	0.009458408557777026
  (0, 225667)	0.02011105901940507
  (0, 232303)	0.0071091958168153805
  (0, 191939)	0.01408748656100091
  (0, 225361)	0.010936822810652582
  (0, 204901)	0.0029793708909773885
  (0, 228350)	0.0046676793959706175
  (0, 39016)	0.016034861908128504
  (0, 190540)	0.010213247014506256
  (0, 217078)	0.015663282366304935
  (0, 211711)	0.011004763936139287
  (0, 205503)	0.0036652511211623952
  (0, 195282)	0.014622196745007743
  (0, 228779)	0.0025895819294109983
  (0, 214049)	0.01190140446222253
  (0, 216966)	0.015349116340140861
  (0, 216225)	0.004114849643535032
  (0, 230811)	0.01267482139788015


Cosine similarity

In [45]:
#Getting the similarity scores using cosine similarity

similarity = cosine_similarity(feature_vectors)

In [46]:
print(similarity)

[[1.         0.57584491 0.82278577 ... 0.31791212 0.07746047 0.15171284]
 [0.57584491 1.         0.58304315 ... 0.28956975 0.0714435  0.13809766]
 [0.82278577 0.58304315 1.         ... 0.33193964 0.0869135  0.15627478]
 ...
 [0.31791212 0.28956975 0.33193964 ... 1.         0.06105104 0.10034212]
 [0.07746047 0.0714435  0.0869135  ... 0.06105104 1.         0.04702882]
 [0.15171284 0.13809766 0.15627478 ... 0.10034212 0.04702882 1.        ]]


In [47]:
print(similarity.shape)

(4803, 4803)


Getting the movie name from the user

In [65]:
#Getting the movie name from the user

movie_name = input('Enter the movie name you want to watch:')

Enter the movie name you want to watch:Interstellar


In [53]:
#Creating a list with all the movie names given in the dataset

list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [54]:
#Finding the close match for the movie name given by the user

find_close_match = difflib.get_close_matches(movie_name,list_of_all_titles)
print(find_close_match)

['Interstellar', 'Cinderella', 'Cinderella Man']


In [55]:
close_match = find_close_match[0]
print(close_match)

Interstellar


In [56]:
#Finding the index of the movie with title

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
print(index_of_the_movie)

95


In [57]:
#Getting a list of similar movies

similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, np.float64(0.7815091877896684)), (1, np.float64(0.5954935940382284)), (2, np.float64(0.7855187713685365)), (3, np.float64(0.8207374046920098)), (4, np.float64(0.76977013377312)), (5, np.float64(0.6650883888154568)), (6, np.float64(0.6396581219451534)), (7, np.float64(0.7098061205423188)), (8, np.float64(0.5668773964764394)), (9, np.float64(0.7694920897223264)), (10, np.float64(0.47605077283913655)), (11, np.float64(0.4283551087592728)), (12, np.float64(0.5329355652793429)), (13, np.float64(0.5676831423727401)), (14, np.float64(0.6765926888386405)), (15, np.float64(0.7187099313281404)), (16, np.float64(0.7774340731231354)), (17, np.float64(0.6122305582553842)), (18, np.float64(0.47218865196859044)), (19, np.float64(0.7779577725409026)), (20, np.float64(0.7739126223864145)), (21, np.float64(0.47796711391223373)), (22, np.float64(0.7650428911287012)), (23, np.float64(0.5820254174097658)), (24, np.float64(0.615890275068875)), (25, np.float64(0.6469546764434024)), (26, np.float64(0.771

In [58]:
len(similarity_score)

4803

In [59]:
#Sorting the movies based on their similarity score

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sorted_similar_movies)

[(95, np.float64(0.9999999999999843)), (3, np.float64(0.8207374046920098)), (212, np.float64(0.8104907498252536)), (223, np.float64(0.8096758918358067)), (412, np.float64(0.806480431591672)), (365, np.float64(0.8063003668645171)), (28, np.float64(0.8038146154064881)), (100, np.float64(0.8017291600893882)), (185, np.float64(0.8002025122057922)), (1430, np.float64(0.7987434329861658)), (363, np.float64(0.798203156156878)), (171, np.float64(0.7980426631673148)), (112, np.float64(0.7969912851763641)), (200, np.float64(0.7968437991982598)), (354, np.float64(0.7968026484830549)), (82, np.float64(0.7949348490770998)), (303, np.float64(0.7947748298726474)), (182, np.float64(0.794648684306205)), (828, np.float64(0.7921367841795196)), (90, np.float64(0.7917577833512758)), (718, np.float64(0.7917163658122589)), (505, np.float64(0.7914957087611297)), (275, np.float64(0.7914355511966423)), (250, np.float64(0.7913933788252535)), (864, np.float64(0.7910560530025855)), (119, np.float64(0.7902416420378

In [62]:
#Print the name of similar movies based on the index

print('Movies suggested for you: \n')

i=1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i,'.',title_from_index)
    i+=1


Movies suggested for you: 

1 . Interstellar
2 . The Dark Knight Rises
3 . The Day After Tomorrow
4 . The Chronicles of Riddick
5 . The Core
6 . Contact
7 . Jurassic World
8 . The Curious Case of Benjamin Button
9 . War of the Worlds
10 . Cursed
11 . A.I. Artificial Intelligence
12 . Master and Commander: The Far Side of the World
13 . Alexander
14 . The Hunger Games: Mockingjay - Part 1
15 . The Girl with the Dragon Tattoo
16 . Dawn of the Planet of the Apes
17 . Catwoman
18 . Ant-Man
19 . Kill Bill: Vol. 1
20 . The Polar Express
21 . Deep Blue Sea
22 . The League of Extraordinary Gentlemen
23 . Minority Report
24 . The Aviator
25 . Blade II
26 . Batman Begins
27 . End of Days
28 . Collateral Damage
29 . Blade: Trinity


Movie Recommendation system

In [63]:
movie_name = input('Enter the movie name you want to watch:')

list_of_all_titles = movies_data['title'].tolist()

find_close_match = difflib.get_close_matches(movie_name,list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)

print('Movies suggested for you: \n')

i=1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i,'.',title_from_index)
    i+=1


Enter the movie name you want to watch:Alexander
Movies suggested for you: 

1 . Alexander
2 . The Core
3 . The Day After Tomorrow
4 . Jurassic World
5 . Cursed
6 . The Aviator
7 . Catwoman
8 . Contact
9 . War of the Worlds
10 . Master and Commander: The Far Side of the World
11 . Harry Potter and the Prisoner of Azkaban
12 . Bad Boys II
13 . The Dark Knight Rises
14 . Minority Report
15 . The League of Extraordinary Gentlemen
16 . Harry Potter and the Chamber of Secrets
17 . The Chronicles of Riddick
18 . Blade II
19 . Hulk
20 . Freddy vs. Jason
21 . Blade: Trinity
22 . Terminator 3: Rise of the Machines
23 . Batman Begins
24 . Kill Bill: Vol. 1
25 . The Wolf of Wall Street
26 . A.I. Artificial Intelligence
27 . Black Hawk Down
28 . The Bourne Supremacy
29 . Collateral Damage
